# HTTP POST Tool
# This tool demonstrates making HTTP POST requests using JSONPlaceholder API
---
apiVersion: ark.mckinsey.com/v1alpha1
kind: Tool
metadata:
  name: write-file-v3
  labels:
    category: io
    method: post
spec:
  type: http
  description: "Write out to a file"
  inputSchema:
    type: object
    properties:
      filename:
        type: string
        description: File Name
      body:
        type: string
        description: File Content
    required: ["filename"]
  http:
    url: http://host.docker.internal:5000/write-file/{filename}
    method: POST
    headers:
      - name: "Content-Type"
        value:
          value: "application/json"
      - name: "Accept"
        value:
          value: "*/*"
      - name: "User-Agent"
        value:
          value: "ARK-Platform/1.0"
    body: |
      {"title": "{{.input.filename}}", "body": "{{.input.body}}", "userId": 1}
    bodyParameters:
      - name: system_name
        value: "ARK Tool System"
    timeout: 30s